name: online_store
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1

dev_dependencies:

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/vectors/
    - assets/images/
    
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_18pt-Black.ttf
          weight: 800  
          
