// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqRdamqfezd1B_sxia7GaHG4yuZRDgO5A',
    appId: '1:740503739892:web:51170f92d06c280f196da1',
    messagingSenderId: '740503739892',
    projectId: 'online-store-6f268',
    authDomain: 'online-store-6f268.firebaseapp.com',
    storageBucket: 'online-store-6f268.appspot.com',
    measurementId: 'G-GL5KSWJFZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvZnVHDrMguZtcNJ_Rchtcd3YZ_zOJkv8',
    appId: '1:740503739892:android:d3296de75b22aac1196da1',
    messagingSenderId: '740503739892',
    projectId: 'online-store-6f268',
    storageBucket: 'online-store-6f268.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCldNXLZmaGXY0uu8a0QUGVqp-ZrI1xIFA',
    appId: '1:740503739892:ios:e0ffc90a13e33712196da1',
    messagingSenderId: '740503739892',
    projectId: 'online-store-6f268',
    storageBucket: 'online-store-6f268.appspot.com',
    iosBundleId: 'com.example.onlineStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCldNXLZmaGXY0uu8a0QUGVqp-ZrI1xIFA',
    appId: '1:740503739892:ios:e0ffc90a13e33712196da1',
    messagingSenderId: '740503739892',
    projectId: 'online-store-6f268',
    storageBucket: 'online-store-6f268.appspot.com',
    iosBundleId: 'com.example.onlineStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqRdamqfezd1B_sxia7GaHG4yuZRDgO5A',
    appId: '1:740503739892:web:a2d821aa19ed9374196da1',
    messagingSenderId: '740503739892',
    projectId: 'online-store-6f268',
    authDomain: 'online-store-6f268.firebaseapp.com',
    storageBucket: 'online-store-6f268.appspot.com',
    measurementId: 'G-BZ0G4VEEZ5',
  );
}
